---
# tasks file for kibana

- name: create kibana directories
  file:
    state=directory
    path={{ item }}
    owner={{ kibana_user }}
    group={{ kibana_group }}
  with_items:
    - "{{ kibana_install_dir }}"
    - "{{ kibana_config_dir }}"
    - "{{ kibana_log_dir }}"
    - "{{ kibana_build_folder }}"

- name: download kibana
  get_url:
    url={{ kibana_url }}
    dest={{ kibana_build_folder }}/{{ kibana_archive }}
  register: kibana_was_downloaded

- name: create kibana group
  group:
    name={{ kibana_group }}
    state=present

- name: create kibna user
  user:
    name={{ kibana_user }}
    group={{ kibana_group }}

- name: copy and unpack
  unarchive:
    src={{ kibana_build_folder }}/{{ kibana_archive }}
    dest={{ kibana_install_dir }}
    copy=no

- name: link to current
  file:
    state=link
    src={{ kibana_install_dir }}/{{ kibana_archive|replace('.tar.gz', '') }}
    path={{ kibana_install_dir }}/current
    owner={{ kibana_user }}
    group={{ kibana_group }}

